# Generated by Django 3.2.6 on 2022-05-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User'},
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'مدیر سیستم'), ('operator', 'اوپراتور'), ('client', 'کاربر')], default='client', max_length=10, verbose_name='roel'),
        ),
    ]
