# Generated by Django 3.2.6 on 2022-05-13 08:50

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220513_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='پست الکترونیک'),
        ),
        migrations.AlterField(
            model_name='user',
            name='father',
            field=models.CharField(blank=True, max_length=150, verbose_name='نام پدر'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ir_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='مشخص می کند که آیا این کاربر فعال است. بجای حذف کاربر تیک این مورد را بردارید', verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخرین ورود'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, max_length=11, verbose_name='موبایل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='کلمه عبور'),
        ),
        migrations.AlterField(
            model_name='user',
            name='register_date',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ ثبت نام'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'مدیر سیستم'), ('operator', 'اوپراتور'), ('client', 'کاربر')], default='client', max_length=10, verbose_name='نقش'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'یک کاربر با این نام کاربری وجود دارد'}, help_text='حداکثر ۱۵۰ کاراکتر شامل حروف و اعداد', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='نام کاربری'),
        ),
        migrations.AlterField(
            model_name='user',
            name='voice_mobile_cost',
            field=models.BigIntegerField(default=700, verbose_name='هزینه پیام صوتی موبایل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='voice_tel_cost',
            field=models.BigIntegerField(default=700, verbose_name='هزینه پیام صوتی تلفن'),
        ),
    ]
