# Generated by Django 4.0.4 on 2022-05-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='register_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت نام'),
        ),
    ]
