# Generated by Django 4.0.4 on 2022-05-13 18:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ تولد'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='father',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='نام پدر'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ir_code',
            field=models.CharField(max_length=10, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='نام خانوادگی'),
        ),
    ]
