# Generated by Django 4.0.4 on 2022-05-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_mobile_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(error_messages={'unique': 'یک کاربر با این شماره موبایل وجود دارد'}, max_length=11, unique=True, verbose_name='موبایل'),
        ),
    ]
