# Generated by Django 4.0.4 on 2022-05-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('secret_code', models.CharField(max_length=20, verbose_name='کد تائید')),
                ('mobile', models.CharField(max_length=11, verbose_name='موبایل')),
            ],
        ),
    ]
