# Generated by Django 4.0.4 on 2022-05-16 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(verbose_name='تاریخ تولد'),
        ),
    ]
