# Generated by Django 4.0.4 on 2022-05-13 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=250, verbose_name='عنوان')),
                ('mobile', models.CharField(blank=True, max_length=11, null=True, verbose_name='موبایل')),
                ('tel', models.CharField(blank=True, max_length=13, null=True, verbose_name='تلفن')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='پست الکترونیک')),
                ('telegram_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='تلگرام')),
                ('whatsapp_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='واتس اپ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نام کاربری')),
            ],
            options={
                'verbose_name': 'مخاطب',
                'verbose_name_plural': 'مخاطبین',
            },
        ),
    ]
