# Generated by Django 4.0.4 on 2022-05-13 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ ایجاد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='فعال'),
        ),
        migrations.AddField(
            model_name='contact',
            name='modify_date',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین ویرایش'),
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین ویرایش')),
                ('caption', models.CharField(max_length=250, verbose_name='عنوان')),
                ('message_type', models.CharField(choices=[('voice', 'صوتی'), ('sms', 'پیامک'), ('email', 'ایمیل'), ('telegram', 'تلگرام'), ('whatsapp', 'واتس اپ')], max_length=10, verbose_name='نوع پیام')),
                ('message_content', models.TextField(verbose_name='محتوای پیام')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نام کاربری')),
            ],
            options={
                'verbose_name': 'قالب پیام',
                'verbose_name_plural': 'قالبهای پیام',
            },
        ),
    ]
