# Generated by Django 4.0.4 on 2022-05-13 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_message_is_active_alter_campaign_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageReceiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین ویرایش')),
                ('status', models.SmallIntegerField(choices=[(1, 'نامشخص'), (2, 'موفق'), (3, 'ناموفق')], default=1, verbose_name='وضعیت')),
                ('send_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ارسال')),
                ('deliver_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تحویل')),
                ('error_number', models.IntegerField(blank=True, null=True, verbose_name='کد خطای ناموفق')),
                ('effort_count', models.SmallIntegerField(blank=True, null=True, verbose_name='تعداد تلاش انجام شده')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contact', verbose_name='مخاطب')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.message', verbose_name='پیام')),
            ],
            options={
                'verbose_name': 'دریافت کننده پیام',
                'verbose_name_plural': 'دریافت کننده های پیام',
            },
        ),
    ]
