# Generated by Django 4.0.4 on 2022-05-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_campaign_is_active_alter_contact_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='labels',
            field=models.ManyToManyField(to='core.messagedefinelabel', verbose_name='برچسب ها'),
        ),
    ]
