# Generated by Django 4.0.4 on 2022-05-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_contactdefinelabel'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='labels',
            field=models.ManyToManyField(blank=True, to='core.contactdefinelabel', verbose_name='برچسب ها'),
        ),
        migrations.AlterField(
            model_name='message',
            name='labels',
            field=models.ManyToManyField(blank=True, to='core.messagedefinelabel', verbose_name='برچسب ها'),
        ),
    ]
