# Generated by Django 4.0.4 on 2022-05-13 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0012_contact_labels_alter_message_labels'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین ویرایش')),
                ('invoice_number', models.BigIntegerField(verbose_name='شماره فاکتور')),
                ('pay_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('amount', models.BigIntegerField(verbose_name='شماره فاکتور')),
                ('pay_code', models.BigIntegerField(verbose_name='کد پیگیری')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نام کاربری')),
            ],
            options={
                'verbose_name': 'فاکتور فروش',
                'verbose_name_plural': 'فاکتور های فروش',
            },
        ),
    ]
