# Generated by Django 4.0.4 on 2022-05-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_invoice_amount_wallet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallet',
            options={'verbose_name': 'کیف پول', 'verbose_name_plural': 'کیف های پول'},
        ),
        migrations.AlterField(
            model_name='wallet',
            name='transaction_type',
            field=models.IntegerField(choices=[(1, 'افزایش اعتبار'), (2, 'عودت وجه'), (3, 'کاهش اعتبار')], verbose_name='نوع تراکنش'),
        ),
    ]
