# Generated by Django 4.0.4 on 2022-05-21 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0015_alter_wallet_options_alter_wallet_transaction_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین ویرایش')),
                ('caption', models.CharField(max_length=250, verbose_name='عنوان')),
                ('message_type', models.CharField(choices=[('voice', 'صوتی'), ('sms', 'پیامک'), ('email', 'ایمیل'), ('telegram', 'تلگرام'), ('whatsapp', 'واتس اپ')], max_length=10, verbose_name='نوع پیام')),
                ('token', models.CharField(blank=True, max_length=250, null=True, verbose_name='شناسه کانال')),
                ('user_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='نام کاربری')),
                ('password', models.CharField(blank=True, max_length=150, null=True, verbose_name='رمز عبور')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نام کاربری')),
            ],
            options={
                'verbose_name': 'کانال',
                'verbose_name_plural': 'کانال ها',
            },
        ),
        migrations.AddField(
            model_name='message',
            name='chanel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.chanel', verbose_name='کانال ارسال'),
        ),
    ]
