# Generated by Django 4.0.4 on 2022-07-15 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_rename_chanel_message_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.campaign', verbose_name='کمپین'),
        ),
    ]
