# Generated by Django 4.0.4 on 2022-07-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_message_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='contact_labels',
            field=models.ManyToManyField(blank=True, to='core.contactdefinelabel', verbose_name='برچسب های مخاطب'),
        ),
    ]
