# Generated by Django 4.0.4 on 2022-07-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_message_contact_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetemplate',
            name='message_length',
            field=models.IntegerField(default=0, verbose_name='طول پیام'),
            preserve_default=False,
        ),
    ]
