# Generated by Django 4.0.4 on 2022-07-29 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0023_messagetemplate_message_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagereceiver',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نام کاربری'),
            preserve_default=False,
        ),
    ]
